# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e1929e4550daa74d465739da5d560745f89153dd15abc857c68840042686a4a8ec1fbd23b0b7649638ad62c7753342dfea86e6e73eb9d4d66d5726fb8c3cdf4

test:
  secret_key_base: 491814eb7d6905dd10a31f4fa6309fd191dda1b592acb9138daf9c6b4e468dae643f5dba95e290c87c8d61fa3082d5b9514c669aabccbf3853eed386d47e709f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
